name: Github Actions - Pull Template Basic
run-name: Running - Sem Mundial - ${{ github.event_name }}
on:
  pull_request:
    branches:
      - main
      - master
  types:
    - opened
    - reopened
    - closed

jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentário
        run: echo "Palmeiras não tem mundial"
