name: Github Actions - Trigger 1
run-name: Running - Trigger 1
on: [push, workflow_dispatch]
jobs: 
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentarios
        run: echo "Palmeiras não tem mundial"
