name: Github Actions - Pull Template Basic
run-name: Sem Mundial - ${{ github.event_name }}

on:
  pull_request

jobs:
  on-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Comentário
        run: echo "Palmeiras não tem mundial"
