name: Github Actions - Push Template Basic
run-name: Running - ${{ github.event_name }} 

on: 
  push:
    paths: 
      - '**.txt'

jobs: 
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Mensagem de log
        run: echo "Checkout - Palmeiras não tem mundial"
