name: Github Actions - Pull Template Basic
run-name: Sem Mundial - ${{ github.event_name }}

on: 
  pull_request

jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentario
        run: echo "Palmeiras não tem mundial"