name:
run-name: Running - Teste com Needs - Depedencia 
on: [push, workflow_dispatch]
jobs:
  test_unit:
    runs-on: ubuntu-latest
    steps:
      - name: Teste unitário
        run: echo "Teste unitário"
      

  test_api:
    needs: test_unit
    runs-on: ubuntu-latest
    steps:
      - name: Teste de API
        run: echo "Teste de API"
    
  test_ui:
    needs: test_api
    runs-on: ubuntu-latest
    steps:
      - name: Teste de UI
        run: echo "Teste de UI"