name: Github Actions - Workflow dispatch Template Basic
run-name: Rodando - ${{ github.event_name }}
on: 
  workflow_dispatch:
    inputs:
      maior-time-br:
        description: mario time BR?
        type: boolean


jobs:
  on-workflow_dispatch:
    runs-on: ubuntu-22.04
    steps:
      - name: Mensagem de log
        run: | 
          echo "Palmeiras não tem mundial ${{inputs.maior-time-br}}"